name: CI

on:
  push:
    branches: [main, master]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [main, master]
    paths-ignore:
      - '**.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: channels
        run: |
          echo "content<<EOF" >> $GITHUB_OUTPUT
          cat manifest/channels.scm >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - uses: PromyLOPh/guix-install-action@v1.6
        with:
          channels: ${{ steps.channels.outputs.content }}
      - run: make ci
